[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NETLIFY_USE_LATEST_NODE_VERSION = "true"
  SECRETS_SCAN_OMIT_KEYS = "VITE_SUPABASE_URL,VITE_SUPABASE_PUBLISHABLE_KEY,VITE_SUPABASE_PROJECT_ID,SIMPLISPAY_PLAN_ID_ANNUAL,SIMPLISPAY_PLAN_ID_MONTHLY,SIMPLISPAY_BASE_URL"
  SECRETS_SCAN_OMIT_PATHS = "supabase/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
