/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as ReferralCodeRouteImport } from './routes/$referralCode'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FSlugRouteImport } from './routes/f.$slug'
import { Route as AuthenticatedTemplatesRouteImport } from './routes/_authenticated/templates'
import { Route as AuthenticatedSuporteRouteImport } from './routes/_authenticated/suporte'
import { Route as AuthenticatedSimuladoresRouteImport } from './routes/_authenticated/simuladores'
import { Route as AuthenticatedIndicarRouteImport } from './routes/_authenticated/indicar'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated/historico'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedAssinaturaRouteImport } from './routes/_authenticated/assinatura'
import { Route as AuthenticatedAssinarRouteImport } from './routes/_authenticated/assinar'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedSimuladoresIndexRouteImport } from './routes/_authenticated/simuladores/index'
import { Route as AuthenticatedFormulariosIndexRouteImport } from './routes/_authenticated/formularios.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedSimuladoresSaidaFinanciamentoRouteImport } from './routes/_authenticated/simuladores/saida-financiamento'
import { Route as AuthenticatedSimuladoresRendaPassivaRouteImport } from './routes/_authenticated/simuladores/renda-passiva'
import { Route as AuthenticatedSimuladoresMetaPatrimonialRouteImport } from './routes/_authenticated/simuladores/meta-patrimonial'
import { Route as AuthenticatedSimuladoresLanceRouteImport } from './routes/_authenticated/simuladores/lance'
import { Route as AuthenticatedSimuladoresFlipCotaRouteImport } from './routes/_authenticated/simuladores/flip-cota'
import { Route as AuthenticatedSimuladoresConsorcioCnpjRouteImport } from './routes/_authenticated/simuladores/consorcio-cnpj'
import { Route as AuthenticatedSimuladoresAluguelVsConsorcioRouteImport } from './routes/_authenticated/simuladores/aluguel-vs-consorcio'
import { Route as AuthenticatedSettingsBrandRouteImport } from './routes/_authenticated/settings.brand'
import { Route as AuthenticatedFormulariosIdRouteImport } from './routes/_authenticated/formularios.$id'
import { Route as AuthenticatedAdminWebhooksRouteImport } from './routes/_authenticated/admin.webhooks'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin.usuarios'
import { Route as AuthenticatedAdminSuporteRouteImport } from './routes/_authenticated/admin.suporte'
import { Route as AuthenticatedAdminFinanceiroRouteImport } from './routes/_authenticated/admin.financeiro'
import { Route as AuthenticatedAdminCamposRouteImport } from './routes/_authenticated/admin.campos'
import { Route as AuthenticatedAdminAssinaturasRouteImport } from './routes/_authenticated/admin.assinaturas'
import { Route as AuthenticatedAdminSimuladoresIndexRouteImport } from './routes/_authenticated/admin.simuladores.index'
import { Route as AuthenticatedSimuladoresEstrategiaSlugRouteImport } from './routes/_authenticated/simuladores/estrategia/$slug'
import { Route as AuthenticatedAdminSimuladoresSlugRouteImport } from './routes/_authenticated/admin.simuladores.$slug'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralCodeRoute = ReferralCodeRouteImport.update({
  id: '/$referralCode',
  path: '/$referralCode',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FSlugRoute = FSlugRouteImport.update({
  id: '/f/$slug',
  path: '/f/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTemplatesRoute = AuthenticatedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSuporteRoute = AuthenticatedSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSimuladoresRoute =
  AuthenticatedSimuladoresRouteImport.update({
    id: '/simuladores',
    path: '/simuladores',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIndicarRoute = AuthenticatedIndicarRouteImport.update({
  id: '/indicar',
  path: '/indicar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAssinaturaRoute = AuthenticatedAssinaturaRouteImport.update({
  id: '/assinatura',
  path: '/assinatura',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAssinarRoute = AuthenticatedAssinarRouteImport.update({
  id: '/assinar',
  path: '/assinar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSimuladoresIndexRoute =
  AuthenticatedSimuladoresIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSimuladoresRoute,
  } as any)
const AuthenticatedFormulariosIndexRoute =
  AuthenticatedFormulariosIndexRouteImport.update({
    id: '/formularios/',
    path: '/formularios/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedSimuladoresSaidaFinanciamentoRoute =
  AuthenticatedSimuladoresSaidaFinanciamentoRouteImport.update({
    id: '/saida-financiamento',
    path: '/saida-financiamento',
    getParentRoute: () => AuthenticatedSimuladoresRoute,
  } as any)
const AuthenticatedSimuladoresRendaPassivaRoute =
  AuthenticatedSimuladoresRendaPassivaRouteImport.update({
    id: '/renda-passiva',
    path: '/renda-passiva',
    getParentRoute: () => AuthenticatedSimuladoresRoute,
  } as any)
const AuthenticatedSimuladoresMetaPatrimonialRoute =
  AuthenticatedSimuladoresMetaPatrimonialRouteImport.update({
    id: '/meta-patrimonial',
    path: '/meta-patrimonial',
    getParentRoute: () => AuthenticatedSimuladoresRoute,
  } as any)
const AuthenticatedSimuladoresLanceRoute =
  AuthenticatedSimuladoresLanceRouteImport.update({
    id: '/lance',
    path: '/lance',
    getParentRoute: () => AuthenticatedSimuladoresRoute,
  } as any)
const AuthenticatedSimuladoresFlipCotaRoute =
  AuthenticatedSimuladoresFlipCotaRouteImport.update({
    id: '/flip-cota',
    path: '/flip-cota',
    getParentRoute: () => AuthenticatedSimuladoresRoute,
  } as any)
const AuthenticatedSimuladoresConsorcioCnpjRoute =
  AuthenticatedSimuladoresConsorcioCnpjRouteImport.update({
    id: '/consorcio-cnpj',
    path: '/consorcio-cnpj',
    getParentRoute: () => AuthenticatedSimuladoresRoute,
  } as any)
const AuthenticatedSimuladoresAluguelVsConsorcioRoute =
  AuthenticatedSimuladoresAluguelVsConsorcioRouteImport.update({
    id: '/aluguel-vs-consorcio',
    path: '/aluguel-vs-consorcio',
    getParentRoute: () => AuthenticatedSimuladoresRoute,
  } as any)
const AuthenticatedSettingsBrandRoute =
  AuthenticatedSettingsBrandRouteImport.update({
    id: '/settings/brand',
    path: '/settings/brand',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFormulariosIdRoute =
  AuthenticatedFormulariosIdRouteImport.update({
    id: '/formularios/$id',
    path: '/formularios/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminWebhooksRoute =
  AuthenticatedAdminWebhooksRouteImport.update({
    id: '/webhooks',
    path: '/webhooks',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSuporteRoute =
  AuthenticatedAdminSuporteRouteImport.update({
    id: '/suporte',
    path: '/suporte',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFinanceiroRoute =
  AuthenticatedAdminFinanceiroRouteImport.update({
    id: '/financeiro',
    path: '/financeiro',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCamposRoute =
  AuthenticatedAdminCamposRouteImport.update({
    id: '/campos',
    path: '/campos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAssinaturasRoute =
  AuthenticatedAdminAssinaturasRouteImport.update({
    id: '/assinaturas',
    path: '/assinaturas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSimuladoresIndexRoute =
  AuthenticatedAdminSimuladoresIndexRouteImport.update({
    id: '/simuladores/',
    path: '/simuladores/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedSimuladoresEstrategiaSlugRoute =
  AuthenticatedSimuladoresEstrategiaSlugRouteImport.update({
    id: '/estrategia/$slug',
    path: '/estrategia/$slug',
    getParentRoute: () => AuthenticatedSimuladoresRoute,
  } as any)
const AuthenticatedAdminSimuladoresSlugRoute =
  AuthenticatedAdminSimuladoresSlugRouteImport.update({
    id: '/simuladores/$slug',
    path: '/simuladores/$slug',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$referralCode': typeof ReferralCodeRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/app': typeof AuthenticatedAppRoute
  '/assinar': typeof AuthenticatedAssinarRoute
  '/assinatura': typeof AuthenticatedAssinaturaRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/indicar': typeof AuthenticatedIndicarRoute
  '/simuladores': typeof AuthenticatedSimuladoresRouteWithChildren
  '/suporte': typeof AuthenticatedSuporteRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/f/$slug': typeof FSlugRoute
  '/admin/assinaturas': typeof AuthenticatedAdminAssinaturasRoute
  '/admin/campos': typeof AuthenticatedAdminCamposRoute
  '/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/admin/suporte': typeof AuthenticatedAdminSuporteRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/webhooks': typeof AuthenticatedAdminWebhooksRoute
  '/formularios/$id': typeof AuthenticatedFormulariosIdRoute
  '/settings/brand': typeof AuthenticatedSettingsBrandRoute
  '/simuladores/aluguel-vs-consorcio': typeof AuthenticatedSimuladoresAluguelVsConsorcioRoute
  '/simuladores/consorcio-cnpj': typeof AuthenticatedSimuladoresConsorcioCnpjRoute
  '/simuladores/flip-cota': typeof AuthenticatedSimuladoresFlipCotaRoute
  '/simuladores/lance': typeof AuthenticatedSimuladoresLanceRoute
  '/simuladores/meta-patrimonial': typeof AuthenticatedSimuladoresMetaPatrimonialRoute
  '/simuladores/renda-passiva': typeof AuthenticatedSimuladoresRendaPassivaRoute
  '/simuladores/saida-financiamento': typeof AuthenticatedSimuladoresSaidaFinanciamentoRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/formularios/': typeof AuthenticatedFormulariosIndexRoute
  '/simuladores/': typeof AuthenticatedSimuladoresIndexRoute
  '/admin/simuladores/$slug': typeof AuthenticatedAdminSimuladoresSlugRoute
  '/simuladores/estrategia/$slug': typeof AuthenticatedSimuladoresEstrategiaSlugRoute
  '/admin/simuladores/': typeof AuthenticatedAdminSimuladoresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$referralCode': typeof ReferralCodeRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app': typeof AuthenticatedAppRoute
  '/assinar': typeof AuthenticatedAssinarRoute
  '/assinatura': typeof AuthenticatedAssinaturaRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/indicar': typeof AuthenticatedIndicarRoute
  '/suporte': typeof AuthenticatedSuporteRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/f/$slug': typeof FSlugRoute
  '/admin/assinaturas': typeof AuthenticatedAdminAssinaturasRoute
  '/admin/campos': typeof AuthenticatedAdminCamposRoute
  '/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/admin/suporte': typeof AuthenticatedAdminSuporteRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/webhooks': typeof AuthenticatedAdminWebhooksRoute
  '/formularios/$id': typeof AuthenticatedFormulariosIdRoute
  '/settings/brand': typeof AuthenticatedSettingsBrandRoute
  '/simuladores/aluguel-vs-consorcio': typeof AuthenticatedSimuladoresAluguelVsConsorcioRoute
  '/simuladores/consorcio-cnpj': typeof AuthenticatedSimuladoresConsorcioCnpjRoute
  '/simuladores/flip-cota': typeof AuthenticatedSimuladoresFlipCotaRoute
  '/simuladores/lance': typeof AuthenticatedSimuladoresLanceRoute
  '/simuladores/meta-patrimonial': typeof AuthenticatedSimuladoresMetaPatrimonialRoute
  '/simuladores/renda-passiva': typeof AuthenticatedSimuladoresRendaPassivaRoute
  '/simuladores/saida-financiamento': typeof AuthenticatedSimuladoresSaidaFinanciamentoRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/formularios': typeof AuthenticatedFormulariosIndexRoute
  '/simuladores': typeof AuthenticatedSimuladoresIndexRoute
  '/admin/simuladores/$slug': typeof AuthenticatedAdminSimuladoresSlugRoute
  '/simuladores/estrategia/$slug': typeof AuthenticatedSimuladoresEstrategiaSlugRoute
  '/admin/simuladores': typeof AuthenticatedAdminSimuladoresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$referralCode': typeof ReferralCodeRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/assinar': typeof AuthenticatedAssinarRoute
  '/_authenticated/assinatura': typeof AuthenticatedAssinaturaRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/_authenticated/indicar': typeof AuthenticatedIndicarRoute
  '/_authenticated/simuladores': typeof AuthenticatedSimuladoresRouteWithChildren
  '/_authenticated/suporte': typeof AuthenticatedSuporteRoute
  '/_authenticated/templates': typeof AuthenticatedTemplatesRoute
  '/f/$slug': typeof FSlugRoute
  '/_authenticated/admin/assinaturas': typeof AuthenticatedAdminAssinaturasRoute
  '/_authenticated/admin/campos': typeof AuthenticatedAdminCamposRoute
  '/_authenticated/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/_authenticated/admin/suporte': typeof AuthenticatedAdminSuporteRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/admin/webhooks': typeof AuthenticatedAdminWebhooksRoute
  '/_authenticated/formularios/$id': typeof AuthenticatedFormulariosIdRoute
  '/_authenticated/settings/brand': typeof AuthenticatedSettingsBrandRoute
  '/_authenticated/simuladores/aluguel-vs-consorcio': typeof AuthenticatedSimuladoresAluguelVsConsorcioRoute
  '/_authenticated/simuladores/consorcio-cnpj': typeof AuthenticatedSimuladoresConsorcioCnpjRoute
  '/_authenticated/simuladores/flip-cota': typeof AuthenticatedSimuladoresFlipCotaRoute
  '/_authenticated/simuladores/lance': typeof AuthenticatedSimuladoresLanceRoute
  '/_authenticated/simuladores/meta-patrimonial': typeof AuthenticatedSimuladoresMetaPatrimonialRoute
  '/_authenticated/simuladores/renda-passiva': typeof AuthenticatedSimuladoresRendaPassivaRoute
  '/_authenticated/simuladores/saida-financiamento': typeof AuthenticatedSimuladoresSaidaFinanciamentoRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/formularios/': typeof AuthenticatedFormulariosIndexRoute
  '/_authenticated/simuladores/': typeof AuthenticatedSimuladoresIndexRoute
  '/_authenticated/admin/simuladores/$slug': typeof AuthenticatedAdminSimuladoresSlugRoute
  '/_authenticated/simuladores/estrategia/$slug': typeof AuthenticatedSimuladoresEstrategiaSlugRoute
  '/_authenticated/admin/simuladores/': typeof AuthenticatedAdminSimuladoresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$referralCode'
    | '/checkout'
    | '/login'
    | '/signup'
    | '/admin'
    | '/app'
    | '/assinar'
    | '/assinatura'
    | '/clientes'
    | '/dashboard'
    | '/historico'
    | '/indicar'
    | '/simuladores'
    | '/suporte'
    | '/templates'
    | '/f/$slug'
    | '/admin/assinaturas'
    | '/admin/campos'
    | '/admin/financeiro'
    | '/admin/suporte'
    | '/admin/usuarios'
    | '/admin/webhooks'
    | '/formularios/$id'
    | '/settings/brand'
    | '/simuladores/aluguel-vs-consorcio'
    | '/simuladores/consorcio-cnpj'
    | '/simuladores/flip-cota'
    | '/simuladores/lance'
    | '/simuladores/meta-patrimonial'
    | '/simuladores/renda-passiva'
    | '/simuladores/saida-financiamento'
    | '/admin/'
    | '/formularios/'
    | '/simuladores/'
    | '/admin/simuladores/$slug'
    | '/simuladores/estrategia/$slug'
    | '/admin/simuladores/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$referralCode'
    | '/checkout'
    | '/login'
    | '/signup'
    | '/app'
    | '/assinar'
    | '/assinatura'
    | '/clientes'
    | '/dashboard'
    | '/historico'
    | '/indicar'
    | '/suporte'
    | '/templates'
    | '/f/$slug'
    | '/admin/assinaturas'
    | '/admin/campos'
    | '/admin/financeiro'
    | '/admin/suporte'
    | '/admin/usuarios'
    | '/admin/webhooks'
    | '/formularios/$id'
    | '/settings/brand'
    | '/simuladores/aluguel-vs-consorcio'
    | '/simuladores/consorcio-cnpj'
    | '/simuladores/flip-cota'
    | '/simuladores/lance'
    | '/simuladores/meta-patrimonial'
    | '/simuladores/renda-passiva'
    | '/simuladores/saida-financiamento'
    | '/admin'
    | '/formularios'
    | '/simuladores'
    | '/admin/simuladores/$slug'
    | '/simuladores/estrategia/$slug'
    | '/admin/simuladores'
  id:
    | '__root__'
    | '/'
    | '/$referralCode'
    | '/_authenticated'
    | '/checkout'
    | '/login'
    | '/signup'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/_authenticated/assinar'
    | '/_authenticated/assinatura'
    | '/_authenticated/clientes'
    | '/_authenticated/dashboard'
    | '/_authenticated/historico'
    | '/_authenticated/indicar'
    | '/_authenticated/simuladores'
    | '/_authenticated/suporte'
    | '/_authenticated/templates'
    | '/f/$slug'
    | '/_authenticated/admin/assinaturas'
    | '/_authenticated/admin/campos'
    | '/_authenticated/admin/financeiro'
    | '/_authenticated/admin/suporte'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/admin/webhooks'
    | '/_authenticated/formularios/$id'
    | '/_authenticated/settings/brand'
    | '/_authenticated/simuladores/aluguel-vs-consorcio'
    | '/_authenticated/simuladores/consorcio-cnpj'
    | '/_authenticated/simuladores/flip-cota'
    | '/_authenticated/simuladores/lance'
    | '/_authenticated/simuladores/meta-patrimonial'
    | '/_authenticated/simuladores/renda-passiva'
    | '/_authenticated/simuladores/saida-financiamento'
    | '/_authenticated/admin/'
    | '/_authenticated/formularios/'
    | '/_authenticated/simuladores/'
    | '/_authenticated/admin/simuladores/$slug'
    | '/_authenticated/simuladores/estrategia/$slug'
    | '/_authenticated/admin/simuladores/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReferralCodeRoute: typeof ReferralCodeRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  FSlugRoute: typeof FSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$referralCode': {
      id: '/$referralCode'
      path: '/$referralCode'
      fullPath: '/$referralCode'
      preLoaderRoute: typeof ReferralCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/$slug': {
      id: '/f/$slug'
      path: '/f/$slug'
      fullPath: '/f/$slug'
      preLoaderRoute: typeof FSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/templates': {
      id: '/_authenticated/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthenticatedTemplatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/suporte': {
      id: '/_authenticated/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof AuthenticatedSuporteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/simuladores': {
      id: '/_authenticated/simuladores'
      path: '/simuladores'
      fullPath: '/simuladores'
      preLoaderRoute: typeof AuthenticatedSimuladoresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/indicar': {
      id: '/_authenticated/indicar'
      path: '/indicar'
      fullPath: '/indicar'
      preLoaderRoute: typeof AuthenticatedIndicarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assinatura': {
      id: '/_authenticated/assinatura'
      path: '/assinatura'
      fullPath: '/assinatura'
      preLoaderRoute: typeof AuthenticatedAssinaturaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assinar': {
      id: '/_authenticated/assinar'
      path: '/assinar'
      fullPath: '/assinar'
      preLoaderRoute: typeof AuthenticatedAssinarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/simuladores/': {
      id: '/_authenticated/simuladores/'
      path: '/'
      fullPath: '/simuladores/'
      preLoaderRoute: typeof AuthenticatedSimuladoresIndexRouteImport
      parentRoute: typeof AuthenticatedSimuladoresRoute
    }
    '/_authenticated/formularios/': {
      id: '/_authenticated/formularios/'
      path: '/formularios'
      fullPath: '/formularios/'
      preLoaderRoute: typeof AuthenticatedFormulariosIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/simuladores/saida-financiamento': {
      id: '/_authenticated/simuladores/saida-financiamento'
      path: '/saida-financiamento'
      fullPath: '/simuladores/saida-financiamento'
      preLoaderRoute: typeof AuthenticatedSimuladoresSaidaFinanciamentoRouteImport
      parentRoute: typeof AuthenticatedSimuladoresRoute
    }
    '/_authenticated/simuladores/renda-passiva': {
      id: '/_authenticated/simuladores/renda-passiva'
      path: '/renda-passiva'
      fullPath: '/simuladores/renda-passiva'
      preLoaderRoute: typeof AuthenticatedSimuladoresRendaPassivaRouteImport
      parentRoute: typeof AuthenticatedSimuladoresRoute
    }
    '/_authenticated/simuladores/meta-patrimonial': {
      id: '/_authenticated/simuladores/meta-patrimonial'
      path: '/meta-patrimonial'
      fullPath: '/simuladores/meta-patrimonial'
      preLoaderRoute: typeof AuthenticatedSimuladoresMetaPatrimonialRouteImport
      parentRoute: typeof AuthenticatedSimuladoresRoute
    }
    '/_authenticated/simuladores/lance': {
      id: '/_authenticated/simuladores/lance'
      path: '/lance'
      fullPath: '/simuladores/lance'
      preLoaderRoute: typeof AuthenticatedSimuladoresLanceRouteImport
      parentRoute: typeof AuthenticatedSimuladoresRoute
    }
    '/_authenticated/simuladores/flip-cota': {
      id: '/_authenticated/simuladores/flip-cota'
      path: '/flip-cota'
      fullPath: '/simuladores/flip-cota'
      preLoaderRoute: typeof AuthenticatedSimuladoresFlipCotaRouteImport
      parentRoute: typeof AuthenticatedSimuladoresRoute
    }
    '/_authenticated/simuladores/consorcio-cnpj': {
      id: '/_authenticated/simuladores/consorcio-cnpj'
      path: '/consorcio-cnpj'
      fullPath: '/simuladores/consorcio-cnpj'
      preLoaderRoute: typeof AuthenticatedSimuladoresConsorcioCnpjRouteImport
      parentRoute: typeof AuthenticatedSimuladoresRoute
    }
    '/_authenticated/simuladores/aluguel-vs-consorcio': {
      id: '/_authenticated/simuladores/aluguel-vs-consorcio'
      path: '/aluguel-vs-consorcio'
      fullPath: '/simuladores/aluguel-vs-consorcio'
      preLoaderRoute: typeof AuthenticatedSimuladoresAluguelVsConsorcioRouteImport
      parentRoute: typeof AuthenticatedSimuladoresRoute
    }
    '/_authenticated/settings/brand': {
      id: '/_authenticated/settings/brand'
      path: '/settings/brand'
      fullPath: '/settings/brand'
      preLoaderRoute: typeof AuthenticatedSettingsBrandRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/formularios/$id': {
      id: '/_authenticated/formularios/$id'
      path: '/formularios/$id'
      fullPath: '/formularios/$id'
      preLoaderRoute: typeof AuthenticatedFormulariosIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/webhooks': {
      id: '/_authenticated/admin/webhooks'
      path: '/webhooks'
      fullPath: '/admin/webhooks'
      preLoaderRoute: typeof AuthenticatedAdminWebhooksRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/suporte': {
      id: '/_authenticated/admin/suporte'
      path: '/suporte'
      fullPath: '/admin/suporte'
      preLoaderRoute: typeof AuthenticatedAdminSuporteRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/financeiro': {
      id: '/_authenticated/admin/financeiro'
      path: '/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AuthenticatedAdminFinanceiroRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/campos': {
      id: '/_authenticated/admin/campos'
      path: '/campos'
      fullPath: '/admin/campos'
      preLoaderRoute: typeof AuthenticatedAdminCamposRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/assinaturas': {
      id: '/_authenticated/admin/assinaturas'
      path: '/assinaturas'
      fullPath: '/admin/assinaturas'
      preLoaderRoute: typeof AuthenticatedAdminAssinaturasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/simuladores/': {
      id: '/_authenticated/admin/simuladores/'
      path: '/simuladores'
      fullPath: '/admin/simuladores/'
      preLoaderRoute: typeof AuthenticatedAdminSimuladoresIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/simuladores/estrategia/$slug': {
      id: '/_authenticated/simuladores/estrategia/$slug'
      path: '/estrategia/$slug'
      fullPath: '/simuladores/estrategia/$slug'
      preLoaderRoute: typeof AuthenticatedSimuladoresEstrategiaSlugRouteImport
      parentRoute: typeof AuthenticatedSimuladoresRoute
    }
    '/_authenticated/admin/simuladores/$slug': {
      id: '/_authenticated/admin/simuladores/$slug'
      path: '/simuladores/$slug'
      fullPath: '/admin/simuladores/$slug'
      preLoaderRoute: typeof AuthenticatedAdminSimuladoresSlugRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAssinaturasRoute: typeof AuthenticatedAdminAssinaturasRoute
  AuthenticatedAdminCamposRoute: typeof AuthenticatedAdminCamposRoute
  AuthenticatedAdminFinanceiroRoute: typeof AuthenticatedAdminFinanceiroRoute
  AuthenticatedAdminSuporteRoute: typeof AuthenticatedAdminSuporteRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminWebhooksRoute: typeof AuthenticatedAdminWebhooksRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminSimuladoresSlugRoute: typeof AuthenticatedAdminSimuladoresSlugRoute
  AuthenticatedAdminSimuladoresIndexRoute: typeof AuthenticatedAdminSimuladoresIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAssinaturasRoute: AuthenticatedAdminAssinaturasRoute,
  AuthenticatedAdminCamposRoute: AuthenticatedAdminCamposRoute,
  AuthenticatedAdminFinanceiroRoute: AuthenticatedAdminFinanceiroRoute,
  AuthenticatedAdminSuporteRoute: AuthenticatedAdminSuporteRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedAdminWebhooksRoute: AuthenticatedAdminWebhooksRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminSimuladoresSlugRoute:
    AuthenticatedAdminSimuladoresSlugRoute,
  AuthenticatedAdminSimuladoresIndexRoute:
    AuthenticatedAdminSimuladoresIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedSimuladoresRouteChildren {
  AuthenticatedSimuladoresAluguelVsConsorcioRoute: typeof AuthenticatedSimuladoresAluguelVsConsorcioRoute
  AuthenticatedSimuladoresConsorcioCnpjRoute: typeof AuthenticatedSimuladoresConsorcioCnpjRoute
  AuthenticatedSimuladoresFlipCotaRoute: typeof AuthenticatedSimuladoresFlipCotaRoute
  AuthenticatedSimuladoresLanceRoute: typeof AuthenticatedSimuladoresLanceRoute
  AuthenticatedSimuladoresMetaPatrimonialRoute: typeof AuthenticatedSimuladoresMetaPatrimonialRoute
  AuthenticatedSimuladoresRendaPassivaRoute: typeof AuthenticatedSimuladoresRendaPassivaRoute
  AuthenticatedSimuladoresSaidaFinanciamentoRoute: typeof AuthenticatedSimuladoresSaidaFinanciamentoRoute
  AuthenticatedSimuladoresIndexRoute: typeof AuthenticatedSimuladoresIndexRoute
  AuthenticatedSimuladoresEstrategiaSlugRoute: typeof AuthenticatedSimuladoresEstrategiaSlugRoute
}

const AuthenticatedSimuladoresRouteChildren: AuthenticatedSimuladoresRouteChildren =
  {
    AuthenticatedSimuladoresAluguelVsConsorcioRoute:
      AuthenticatedSimuladoresAluguelVsConsorcioRoute,
    AuthenticatedSimuladoresConsorcioCnpjRoute:
      AuthenticatedSimuladoresConsorcioCnpjRoute,
    AuthenticatedSimuladoresFlipCotaRoute:
      AuthenticatedSimuladoresFlipCotaRoute,
    AuthenticatedSimuladoresLanceRoute: AuthenticatedSimuladoresLanceRoute,
    AuthenticatedSimuladoresMetaPatrimonialRoute:
      AuthenticatedSimuladoresMetaPatrimonialRoute,
    AuthenticatedSimuladoresRendaPassivaRoute:
      AuthenticatedSimuladoresRendaPassivaRoute,
    AuthenticatedSimuladoresSaidaFinanciamentoRoute:
      AuthenticatedSimuladoresSaidaFinanciamentoRoute,
    AuthenticatedSimuladoresIndexRoute: AuthenticatedSimuladoresIndexRoute,
    AuthenticatedSimuladoresEstrategiaSlugRoute:
      AuthenticatedSimuladoresEstrategiaSlugRoute,
  }

const AuthenticatedSimuladoresRouteWithChildren =
  AuthenticatedSimuladoresRoute._addFileChildren(
    AuthenticatedSimuladoresRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedAssinarRoute: typeof AuthenticatedAssinarRoute
  AuthenticatedAssinaturaRoute: typeof AuthenticatedAssinaturaRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedIndicarRoute: typeof AuthenticatedIndicarRoute
  AuthenticatedSimuladoresRoute: typeof AuthenticatedSimuladoresRouteWithChildren
  AuthenticatedSuporteRoute: typeof AuthenticatedSuporteRoute
  AuthenticatedTemplatesRoute: typeof AuthenticatedTemplatesRoute
  AuthenticatedFormulariosIdRoute: typeof AuthenticatedFormulariosIdRoute
  AuthenticatedSettingsBrandRoute: typeof AuthenticatedSettingsBrandRoute
  AuthenticatedFormulariosIndexRoute: typeof AuthenticatedFormulariosIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedAssinarRoute: AuthenticatedAssinarRoute,
  AuthenticatedAssinaturaRoute: AuthenticatedAssinaturaRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedIndicarRoute: AuthenticatedIndicarRoute,
  AuthenticatedSimuladoresRoute: AuthenticatedSimuladoresRouteWithChildren,
  AuthenticatedSuporteRoute: AuthenticatedSuporteRoute,
  AuthenticatedTemplatesRoute: AuthenticatedTemplatesRoute,
  AuthenticatedFormulariosIdRoute: AuthenticatedFormulariosIdRoute,
  AuthenticatedSettingsBrandRoute: AuthenticatedSettingsBrandRoute,
  AuthenticatedFormulariosIndexRoute: AuthenticatedFormulariosIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReferralCodeRoute: ReferralCodeRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  FSlugRoute: FSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
