/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTemplatesRouteImport } from './routes/_authenticated/templates'
import { Route as AuthenticatedSuporteRouteImport } from './routes/_authenticated/suporte'
import { Route as AuthenticatedSimuladoresRouteImport } from './routes/_authenticated/simuladores'
import { Route as AuthenticatedSimuladoresLanceRouteImport } from './routes/_authenticated/simuladores/lance'
import { Route as AuthenticatedSimuladoresAluguelVsConsorcioRouteImport } from './routes/_authenticated/simuladores/aluguel-vs-consorcio'
import { Route as AuthenticatedSimuladoresRendaPassivaRouteImport } from './routes/_authenticated/simuladores/renda-passiva'
import { Route as AuthenticatedSimuladoresFlipCotaRouteImport } from './routes/_authenticated/simuladores/flip-cota'
import { Route as AuthenticatedSimuladoresEstrategiaSlugRouteImport } from './routes/_authenticated/simuladores/estrategia/$slug'
import { Route as AuthenticatedSimuladoresSaidaFinanciamentoRouteImport } from './routes/_authenticated/simuladores/saida-financiamento'
import { Route as AuthenticatedSimuladoresMetaPatrimonialRouteImport } from './routes/_authenticated/simuladores/meta-patrimonial'
import { Route as AuthenticatedSimuladoresConsorcioCNPJRouteImport } from './routes/_authenticated/simuladores/consorcio-cnpj'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated/historico'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedAssinaturaRouteImport } from './routes/_authenticated/assinatura'
import { Route as AuthenticatedAssinarRouteImport } from './routes/_authenticated/assinar'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminWebhooksRouteImport } from './routes/_authenticated/admin.webhooks'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin.usuarios'
import { Route as AuthenticatedAdminSuporteRouteImport } from './routes/_authenticated/admin.suporte'
import { Route as AuthenticatedAdminFinanceiroRouteImport } from './routes/_authenticated/admin.financeiro'
import { Route as AuthenticatedAdminAssinaturasRouteImport } from './routes/_authenticated/admin.assinaturas'
import { Route as AuthenticatedAdminSimuladoresRouteImport } from './routes/_authenticated/admin.simuladores'
import { Route as AuthenticatedAdminSimuladoresSlugRouteImport } from './routes/_authenticated/admin.simuladores.$slug'
import { Route as AuthenticatedIndicarRouteImport } from './routes/_authenticated/indicar'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTemplatesRoute = AuthenticatedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSuporteRoute = AuthenticatedSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSimuladoresRoute =
  AuthenticatedSimuladoresRouteImport.update({
    id: '/simuladores',
    path: '/simuladores',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSimuladoresLanceRoute =
  AuthenticatedSimuladoresLanceRouteImport.update({
    id: '/simuladores/lance',
    path: '/simuladores/lance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSimuladoresAluguelVsConsorcioRoute =
  AuthenticatedSimuladoresAluguelVsConsorcioRouteImport.update({
    id: '/simuladores/aluguel-vs-consorcio',
    path: '/simuladores/aluguel-vs-consorcio',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSimuladoresRendaPassivaRoute =
  AuthenticatedSimuladoresRendaPassivaRouteImport.update({
    id: '/simuladores/renda-passiva',
    path: '/simuladores/renda-passiva',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSimuladoresFlipCotaRoute =
  AuthenticatedSimuladoresFlipCotaRouteImport.update({
    id: '/simuladores/flip-cota',
    path: '/simuladores/flip-cota',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSimuladoresEstrategiaSlugRoute =
  AuthenticatedSimuladoresEstrategiaSlugRouteImport.update({
    id: '/simuladores/estrategia/$slug',
    path: '/simuladores/estrategia/$slug',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSimuladoresSaidaFinanciamentoRoute =
  AuthenticatedSimuladoresSaidaFinanciamentoRouteImport.update({
    id: '/simuladores/saida-financiamento',
    path: '/simuladores/saida-financiamento',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSimuladoresMetaPatrimonialRoute =
  AuthenticatedSimuladoresMetaPatrimonialRouteImport.update({
    id: '/simuladores/meta-patrimonial',
    path: '/simuladores/meta-patrimonial',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSimuladoresConsorcioCNPJRoute =
  AuthenticatedSimuladoresConsorcioCNPJRouteImport.update({
    id: '/simuladores/consorcio-cnpj',
    path: '/simuladores/consorcio-cnpj',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAssinaturaRoute = AuthenticatedAssinaturaRouteImport.update({
  id: '/assinatura',
  path: '/assinatura',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAssinarRoute = AuthenticatedAssinarRouteImport.update({
  id: '/assinar',
  path: '/assinar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminWebhooksRoute =
  AuthenticatedAdminWebhooksRouteImport.update({
    id: '/webhooks',
    path: '/webhooks',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSuporteRoute =
  AuthenticatedAdminSuporteRouteImport.update({
    id: '/suporte',
    path: '/suporte',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFinanceiroRoute =
  AuthenticatedAdminFinanceiroRouteImport.update({
    id: '/financeiro',
    path: '/financeiro',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAssinaturasRoute =
  AuthenticatedAdminAssinaturasRouteImport.update({
    id: '/assinaturas',
    path: '/assinaturas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSimuladoresRoute =
  AuthenticatedAdminSimuladoresRouteImport.update({
    id: '/_authenticated/admin/simuladores',
    path: '/admin/simuladores',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIndicarRoute = AuthenticatedIndicarRouteImport.update({
  id: '/indicar',
  path: '/indicar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminSimuladoresSlugRoute =
  AuthenticatedAdminSimuladoresSlugRouteImport.update({
    id: '/_authenticated/admin/simuladores/$slug',
    path: '/admin/simuladores/$slug',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/app': typeof AuthenticatedAppRoute
  '/assinar': typeof AuthenticatedAssinarRoute
  '/assinatura': typeof AuthenticatedAssinaturaRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/indicar': typeof AuthenticatedIndicarRoute
  '/simuladores': typeof AuthenticatedSimuladoresRoute
  '/simuladores/lance': typeof AuthenticatedSimuladoresLanceRoute
  '/simuladores/aluguel-vs-consorcio': typeof AuthenticatedSimuladoresAluguelVsConsorcioRoute
  '/simuladores/renda-passiva': typeof AuthenticatedSimuladoresRendaPassivaRoute
  '/simuladores/flip-cota': typeof AuthenticatedSimuladoresFlipCotaRoute
  '/simuladores/estrategia/$slug': typeof AuthenticatedSimuladoresEstrategiaSlugRoute
  '/simuladores/saida-financiamento': typeof AuthenticatedSimuladoresSaidaFinanciamentoRoute
  '/simuladores/meta-patrimonial': typeof AuthenticatedSimuladoresMetaPatrimonialRoute
  '/simuladores/consorcio-cnpj': typeof AuthenticatedSimuladoresConsorcioCNPJRoute
  '/suporte': typeof AuthenticatedSuporteRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/admin/assinaturas': typeof AuthenticatedAdminAssinaturasRoute
  '/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/admin/suporte': typeof AuthenticatedAdminSuporteRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/webhooks': typeof AuthenticatedAdminWebhooksRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/simuladores': typeof AuthenticatedAdminSimuladoresRoute
  '/admin/simuladores/$slug': typeof AuthenticatedAdminSimuladoresSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app': typeof AuthenticatedAppRoute
  '/assinar': typeof AuthenticatedAssinarRoute
  '/assinatura': typeof AuthenticatedAssinaturaRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/indicar': typeof AuthenticatedIndicarRoute
  '/simuladores': typeof AuthenticatedSimuladoresRoute
  '/simuladores/lance': typeof AuthenticatedSimuladoresLanceRoute
  '/simuladores/aluguel-vs-consorcio': typeof AuthenticatedSimuladoresAluguelVsConsorcioRoute
  '/simuladores/renda-passiva': typeof AuthenticatedSimuladoresRendaPassivaRoute
  '/simuladores/flip-cota': typeof AuthenticatedSimuladoresFlipCotaRoute
  '/simuladores/estrategia/$slug': typeof AuthenticatedSimuladoresEstrategiaSlugRoute
  '/simuladores/saida-financiamento': typeof AuthenticatedSimuladoresSaidaFinanciamentoRoute
  '/simuladores/meta-patrimonial': typeof AuthenticatedSimuladoresMetaPatrimonialRoute
  '/simuladores/consorcio-cnpj': typeof AuthenticatedSimuladoresConsorcioCNPJRoute
  '/suporte': typeof AuthenticatedSuporteRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/admin/assinaturas': typeof AuthenticatedAdminAssinaturasRoute
  '/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/admin/suporte': typeof AuthenticatedAdminSuporteRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/webhooks': typeof AuthenticatedAdminWebhooksRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/simuladores': typeof AuthenticatedAdminSimuladoresRoute
  '/admin/simuladores/$slug': typeof AuthenticatedAdminSimuladoresSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/assinar': typeof AuthenticatedAssinarRoute
  '/_authenticated/assinatura': typeof AuthenticatedAssinaturaRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/_authenticated/indicar': typeof AuthenticatedIndicarRoute
  '/_authenticated/simuladores': typeof AuthenticatedSimuladoresRoute
  '/_authenticated/simuladores/lance': typeof AuthenticatedSimuladoresLanceRoute
  '/_authenticated/simuladores/aluguel-vs-consorcio': typeof AuthenticatedSimuladoresAluguelVsConsorcioRoute
  '/_authenticated/simuladores/renda-passiva': typeof AuthenticatedSimuladoresRendaPassivaRoute
  '/_authenticated/simuladores/flip-cota': typeof AuthenticatedSimuladoresFlipCotaRoute
  '/_authenticated/simuladores/estrategia/$slug': typeof AuthenticatedSimuladoresEstrategiaSlugRoute
  '/_authenticated/simuladores/saida-financiamento': typeof AuthenticatedSimuladoresSaidaFinanciamentoRoute
  '/_authenticated/simuladores/meta-patrimonial': typeof AuthenticatedSimuladoresMetaPatrimonialRoute
  '/_authenticated/simuladores/consorcio-cnpj': typeof AuthenticatedSimuladoresConsorcioCNPJRoute
  '/_authenticated/suporte': typeof AuthenticatedSuporteRoute
  '/_authenticated/templates': typeof AuthenticatedTemplatesRoute
  '/_authenticated/admin/assinaturas': typeof AuthenticatedAdminAssinaturasRoute
  '/_authenticated/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/_authenticated/admin/suporte': typeof AuthenticatedAdminSuporteRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/admin/webhooks': typeof AuthenticatedAdminWebhooksRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/simuladores': typeof AuthenticatedAdminSimuladoresRoute
  '/_authenticated/admin/simuladores/$slug': typeof AuthenticatedAdminSimuladoresSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/login'
    | '/signup'
    | '/admin'
    | '/app'
    | '/assinar'
    | '/assinatura'
    | '/clientes'
    | '/dashboard'
    | '/historico'
    | '/indicar'
    | '/simuladores'
    | '/simuladores/lance'
    | '/simuladores/aluguel-vs-consorcio'
    | '/simuladores/renda-passiva'
    | '/simuladores/flip-cota'
    | '/simuladores/estrategia/$slug'
    | '/simuladores/saida-financiamento'
    | '/simuladores/meta-patrimonial'
    | '/simuladores/consorcio-cnpj'
    | '/suporte'
    | '/templates'
    | '/admin/assinaturas'
    | '/admin/financeiro'
    | '/admin/suporte'
    | '/admin/usuarios'
    | '/admin/webhooks'
    | '/admin/'
    | '/admin/simuladores'
    | '/admin/simuladores/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/login'
    | '/signup'
    | '/app'
    | '/assinar'
    | '/assinatura'
    | '/clientes'
    | '/dashboard'
    | '/historico'
    | '/indicar'
    | '/simuladores'
    | '/simuladores/lance'
    | '/simuladores/aluguel-vs-consorcio'
    | '/simuladores/renda-passiva'
    | '/simuladores/flip-cota'
    | '/simuladores/estrategia/$slug'
    | '/simuladores/saida-financiamento'
    | '/simuladores/meta-patrimonial'
    | '/simuladores/consorcio-cnpj'
    | '/suporte'
    | '/templates'
    | '/admin/assinaturas'
    | '/admin/financeiro'
    | '/admin/suporte'
    | '/admin/usuarios'
    | '/admin/webhooks'
    | '/admin'
    | '/admin/simuladores'
    | '/admin/simuladores/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/checkout'
    | '/login'
    | '/signup'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/_authenticated/assinar'
    | '/_authenticated/assinatura'
    | '/_authenticated/clientes'
    | '/_authenticated/dashboard'
    | '/_authenticated/historico'
    | '/_authenticated/indicar'
    | '/_authenticated/simuladores'
    | '/_authenticated/simuladores/lance'
    | '/_authenticated/simuladores/aluguel-vs-consorcio'
    | '/_authenticated/simuladores/renda-passiva'
    | '/_authenticated/simuladores/flip-cota'
    | '/_authenticated/simuladores/estrategia/$slug'
    | '/_authenticated/simuladores/saida-financiamento'
    | '/_authenticated/simuladores/meta-patrimonial'
    | '/_authenticated/simuladores/consorcio-cnpj'
    | '/_authenticated/suporte'
    | '/_authenticated/templates'
    | '/_authenticated/admin/assinaturas'
    | '/_authenticated/admin/financeiro'
    | '/_authenticated/admin/suporte'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/admin/webhooks'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/simuladores'
    | '/_authenticated/admin/simuladores/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/templates': {
      id: '/_authenticated/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthenticatedTemplatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/suporte': {
      id: '/_authenticated/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof AuthenticatedSuporteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/simuladores': {
      id: '/_authenticated/simuladores'
      path: '/simuladores'
      fullPath: '/simuladores'
      preLoaderRoute: typeof AuthenticatedSimuladoresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/simuladores/lance': {
      id: '/_authenticated/simuladores/lance'
      path: '/simuladores/lance'
      fullPath: '/simuladores/lance'
      preLoaderRoute: typeof AuthenticatedSimuladoresLanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/simuladores/aluguel-vs-consorcio': {
      id: '/_authenticated/simuladores/aluguel-vs-consorcio'
      path: '/simuladores/aluguel-vs-consorcio'
      fullPath: '/simuladores/aluguel-vs-consorcio'
      preLoaderRoute: typeof AuthenticatedSimuladoresAluguelVsConsorcioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/simuladores/renda-passiva': {
      id: '/_authenticated/simuladores/renda-passiva'
      path: '/simuladores/renda-passiva'
      fullPath: '/simuladores/renda-passiva'
      preLoaderRoute: typeof AuthenticatedSimuladoresRendaPassivaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/simuladores/flip-cota': {
      id: '/_authenticated/simuladores/flip-cota'
      path: '/simuladores/flip-cota'
      fullPath: '/simuladores/flip-cota'
      preLoaderRoute: typeof AuthenticatedSimuladoresFlipCotaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/simuladores/estrategia/$slug': {
      id: '/_authenticated/simuladores/estrategia/$slug'
      path: '/simuladores/estrategia/$slug'
      fullPath: '/simuladores/estrategia/$slug'
      preLoaderRoute: typeof AuthenticatedSimuladoresEstrategiaSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/simuladores/saida-financiamento': {
      id: '/_authenticated/simuladores/saida-financiamento'
      path: '/simuladores/saida-financiamento'
      fullPath: '/simuladores/saida-financiamento'
      preLoaderRoute: typeof AuthenticatedSimuladoresSaidaFinanciamentoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/simuladores/meta-patrimonial': {
      id: '/_authenticated/simuladores/meta-patrimonial'
      path: '/simuladores/meta-patrimonial'
      fullPath: '/simuladores/meta-patrimonial'
      preLoaderRoute: typeof AuthenticatedSimuladoresMetaPatrimonialRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/simuladores/consorcio-cnpj': {
      id: '/_authenticated/simuladores/consorcio-cnpj'
      path: '/simuladores/consorcio-cnpj'
      fullPath: '/simuladores/consorcio-cnpj'
      preLoaderRoute: typeof AuthenticatedSimuladoresConsorcioCNPJRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assinatura': {
      id: '/_authenticated/assinatura'
      path: '/assinatura'
      fullPath: '/assinatura'
      preLoaderRoute: typeof AuthenticatedAssinaturaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/indicar': {
      id: '/_authenticated/indicar'
      path: '/indicar'
      fullPath: '/indicar'
      preLoaderRoute: typeof AuthenticatedIndicarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assinar': {
      id: '/_authenticated/assinar'
      path: '/assinar'
      fullPath: '/assinar'
      preLoaderRoute: typeof AuthenticatedAssinarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/webhooks': {
      id: '/_authenticated/admin/webhooks'
      path: '/webhooks'
      fullPath: '/admin/webhooks'
      preLoaderRoute: typeof AuthenticatedAdminWebhooksRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/suporte': {
      id: '/_authenticated/admin/suporte'
      path: '/suporte'
      fullPath: '/admin/suporte'
      preLoaderRoute: typeof AuthenticatedAdminSuporteRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/financeiro': {
      id: '/_authenticated/admin/financeiro'
      path: '/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AuthenticatedAdminFinanceiroRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/assinaturas': {
      id: '/_authenticated/admin/assinaturas'
      path: '/assinaturas'
      fullPath: '/admin/assinaturas'
      preLoaderRoute: typeof AuthenticatedAdminAssinaturasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/simuladores': {
      id: '/_authenticated/admin/simuladores'
      path: '/admin/simuladores'
      fullPath: '/admin/simuladores'
      preLoaderRoute: typeof AuthenticatedAdminSimuladoresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/simuladores/$slug': {
      id: '/_authenticated/admin/simuladores/$slug'
      path: '/admin/simuladores/$slug'
      fullPath: '/admin/simuladores/$slug'
      preLoaderRoute: typeof AuthenticatedAdminSimuladoresSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAssinaturasRoute: typeof AuthenticatedAdminAssinaturasRoute
  AuthenticatedAdminFinanceiroRoute: typeof AuthenticatedAdminFinanceiroRoute
  AuthenticatedAdminSuporteRoute: typeof AuthenticatedAdminSuporteRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminWebhooksRoute: typeof AuthenticatedAdminWebhooksRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAssinaturasRoute: AuthenticatedAdminAssinaturasRoute,
  AuthenticatedAdminFinanceiroRoute: AuthenticatedAdminFinanceiroRoute,
  AuthenticatedAdminSuporteRoute: AuthenticatedAdminSuporteRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedAdminWebhooksRoute: AuthenticatedAdminWebhooksRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedAssinarRoute: typeof AuthenticatedAssinarRoute
  AuthenticatedAssinaturaRoute: typeof AuthenticatedAssinaturaRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedIndicarRoute: typeof AuthenticatedIndicarRoute
  AuthenticatedSimuladoresRoute: typeof AuthenticatedSimuladoresRoute
  AuthenticatedSimuladoresLanceRoute: typeof AuthenticatedSimuladoresLanceRoute
  AuthenticatedSimuladoresAluguelVsConsorcioRoute: typeof AuthenticatedSimuladoresAluguelVsConsorcioRoute
  AuthenticatedSimuladoresRendaPassivaRoute: typeof AuthenticatedSimuladoresRendaPassivaRoute
  AuthenticatedSimuladoresFlipCotaRoute: typeof AuthenticatedSimuladoresFlipCotaRoute
  AuthenticatedSimuladoresEstrategiaSlugRoute: typeof AuthenticatedSimuladoresEstrategiaSlugRoute
  AuthenticatedSimuladoresSaidaFinanciamentoRoute: typeof AuthenticatedSimuladoresSaidaFinanciamentoRoute
  AuthenticatedSimuladoresMetaPatrimonialRoute: typeof AuthenticatedSimuladoresMetaPatrimonialRoute
  AuthenticatedSimuladoresConsorcioCNPJRoute: typeof AuthenticatedSimuladoresConsorcioCNPJRoute
  AuthenticatedSuporteRoute: typeof AuthenticatedSuporteRoute
  AuthenticatedTemplatesRoute: typeof AuthenticatedTemplatesRoute
  AuthenticatedAdminSimuladoresRoute: typeof AuthenticatedAdminSimuladoresRoute
  AuthenticatedAdminSimuladoresSlugRoute: typeof AuthenticatedAdminSimuladoresSlugRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedAssinarRoute: AuthenticatedAssinarRoute,
  AuthenticatedAssinaturaRoute: AuthenticatedAssinaturaRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedIndicarRoute: AuthenticatedIndicarRoute,
  AuthenticatedSimuladoresRoute: AuthenticatedSimuladoresRoute,
  AuthenticatedSimuladoresLanceRoute: AuthenticatedSimuladoresLanceRoute,
  AuthenticatedSimuladoresAluguelVsConsorcioRoute: AuthenticatedSimuladoresAluguelVsConsorcioRoute,
  AuthenticatedSimuladoresRendaPassivaRoute: AuthenticatedSimuladoresRendaPassivaRoute,
  AuthenticatedSimuladoresFlipCotaRoute: AuthenticatedSimuladoresFlipCotaRoute,
  AuthenticatedSimuladoresEstrategiaSlugRoute: AuthenticatedSimuladoresEstrategiaSlugRoute,
  AuthenticatedSimuladoresSaidaFinanciamentoRoute: AuthenticatedSimuladoresSaidaFinanciamentoRoute,
  AuthenticatedSimuladoresMetaPatrimonialRoute: AuthenticatedSimuladoresMetaPatrimonialRoute,
  AuthenticatedSimuladoresConsorcioCNPJRoute: AuthenticatedSimuladoresConsorcioCNPJRoute,
  AuthenticatedSuporteRoute: AuthenticatedSuporteRoute,
  AuthenticatedTemplatesRoute: AuthenticatedTemplatesRoute,
  AuthenticatedAdminSimuladoresRoute: AuthenticatedAdminSimuladoresRoute,
  AuthenticatedAdminSimuladoresSlugRoute: AuthenticatedAdminSimuladoresSlugRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
